version: '3'

services:
  tp_server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 8080:8080
    volumes:
      - .:/app
  tp_client:
    build:
      context: .
      dockerfile: Dockerfile.client
    volumes:
      - .:/app
